version: "3.0"

services:

  bu-service:
    image: ghcr.io/larc-logs-transparentes/bu-service:latest
    container_name: hom-logst-bu-service
    hostname: bu-service
    network_mode: "host"
    environment:
      MONGO_URL: "${BU_SERVICE_MONGO_URL}"
      TL_MANAGER_URL: "${TL_MANAGER_URL}"
      TREE_NAME_PREFIX: "eleicao_"
      TREE_DEFAULT_COMMITMENT_SIZE: 8

    
  back-pub:
    image: ghcr.io/larc-logs-transparentes/back-pub:latest
    container_name: hom-logst-back-pub
    hostname: back-pub
    depends_on:
      - bu-service
    network_mode: "host"
    volumes:
      - ./backend.public.config.json:/app/src/config.json


  frontend:
    image: ghcr.io/larc-logs-transparentes/frontend:latest
    container_name: hom-logst-frontend
    hostname: frontend
    depends_on:
      - back-pub
      - bu-service
    network_mode: "host"
    volumes:
      - ./frontend.config.json:/app/src/config.json


  tlmanager:
    image: ghcr.io/larc-logs-transparentes/tlmanager:latest
    container_name: hom-tlmanager
    hostname: tlmanager
    depends_on:
      - back-pub
    network_mode: "host"
    volumes:
      - ${TL_MANAGER_PUB_KEY_PATH}:/app/keys/public_key.pem
      - ${TL_MANAGER_PRIV_KEY_PATH}:/app/keys/private_key.pem
    environment:
      URL: "${TL_MANAGER_MONGO_URL}"

