version: "3.0"

networks:
  demo-logst:

services:

  mongo-logst:
    image: mongo:6.0.14
    container_name: demo-mongo-logst
    hostname: mongo-logst
    networks:
      - demo-logst
    volumes:
      - ./mongo.init.js:/docker-entrypoint-initdb.d/mongo.init.js
#    ports :
#        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
  
  bu-service:
    image: ghcr.io/larc-logs-transparentes/bu-service:latest
    container_name: demo-logst-bu-service
    hostname: bu-service
    depends_on:
      - mongo-logst
    networks:
      - demo-logst
    ports:
      - 9090:9090
    environment:
      MONGO_URL: "mongodb://buuser:bupassword@mongo-logst/bu_service"
      TL_MANAGER_URL: "http://tlmanager:8000"
      TREE_NAME_PREFIX: "eleicao_"
      TREE_DEFAULT_COMMITMENT_SIZE: 8

    
  back-pub:
    image: ghcr.io/larc-logs-transparentes/back-pub:latest
    container_name: demo-logst-back-pub
    hostname: back-pub
    depends_on:
      - bu-service
      - mongo-logst
    networks:
      - demo-logst
    volumes:
      - ./backend.public.config.json:/app/src/config.json
    ports:
      - 8080:8080


  frontend:
    image: ghcr.io/larc-logs-transparentes/frontend:latest
    container_name: demo-logst-frontend
    hostname: frontend
    depends_on:
      - back-pub
      - tlmanager
    networks:
      - demo-logst
    volumes:
      - ./frontend.config.json:/app/src/config.json
    ports:
      - 3000:3000


  tlmanager:
    image: ghcr.io/larc-logs-transparentes/tlmanager:latest
    container_name: demo-tlmanager
    hostname: tlmanager
    depends_on:
      - back-pub
      - mongo-logst
    networks:
      - demo-logst
#    ports:
#      - 8000:8000
    environment:
      URL: "mongodb://tluser:tlpassword@mongo-logst:27017/tlmanager"

